root: true
extends:
- airbnb-base
globals:
  AWSCognito: true
env:
  browser: true
rules:
  # Git-controlled
  linebreak-style: off
  # sjcl hmac breaks new-cap
  new-cap:
  - error
  - newIsCapExceptions:
    - sjcl.misc.hmac
  valid-jsdoc: error
  require-jsdoc:
  - error
  - require:
      FunctionDeclaration: true
      ClassDeclaration: true
      MethodDefinition: true
